version: '3.3'
services:
  observability:
    image: jaegertracing/all-in-one:1.38
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - back-tier

  random-meme:
    image: hasankhatib/random-meme
    build: .
    environment:
      - JAEGER_URI="http://observability:14268/api/traces"
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
    ports:
      - "8080:8080"
    networks:
      - back-tier
    depends_on:
      - observability

networks:
  back-tier: