version: '3.3'
services:
  observability:
    image: jaegertracing/all-in-one:1.38
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - meme-net

  meme-service:
    image: hasankhatib/random-meme:latest
    build: .
    environment:
      - JAEGER_URI=http://observability:14268/api/traces
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - meme-net
    depends_on:
      - observability
  
  api-gateway:
    image: hasankhatib/api-gateway
    build: .
    environment:
      - API_USER=user
      - API_PASS=pass
      - BE_SERVICE_URL=http://meme-service:8080/
      - JAEGER_URI=http://observability:14268/api/traces
    networks:
      - meme-net
    ports:
      - "8081:8081"
    depends_on:
      - meme-service

networks:
  meme-net: